[workspace]
resolver = "2"
members = [
    "crates/omega-sh",
    "crates/omega-loop-client",
    "crates/cli",
    "crates/omega-llm",
    "crates/omega-core",
    "crates/omega-loop",
    "crates/omega-tui",
    "crates/omega-sh-client",
    "crates/omega-tools",
    "crates/omega-tool-defs",
    "crates/clankersh",
]
